pf_r2000:
  ros__parameters:
    transport: "udp"
    scanner_ip: "192.168.60.100"
    # port: "3000" # optional
    device: "R2000"
    start_angle: -1800000
    max_num_points_scan: 0
    packet_type: "C"
    scan_topic: "/pf/scan"
    frame_id: "lidar_v1_1"
    watchdogtimeout: 60000
    watchdog: true
