controller_manager:
  ros__parameters:
    # Joint State Controller --------------------------------------
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

    # Position Controllers ----------------------------------------
    joint_right_position_controller:
      type: position_controllers/JointPositionController
      joint: joint_right
      pid:
        p: 21.0
        i: 0.01
        d: 10.0

    left_joint_position_controller:
      type: position_controllers/JointPositionController
      joint: left_joint
      pid:
        p: 21.0
        i: 0.01
        d: 10.0
